apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscribe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscribe
  template:
    metadata:
      labels:
        app: subscribe
    spec:
      containers:
        - name: subscribe
          image: ahmedmuraat/subscribe:latest
          ports:
            - containerPort: 8082
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          volumeMounts:
            - name: certs
              mountPath: /app/certs
      volumes:
        - name: certs
          hostPath:
            path: /path/to/your/certs
---
apiVersion: v1
kind: Service
metadata:
  name: subscribe
spec:
  selector:
    app: subscribe
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8082
