apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflixclone
  labels:
    app: netflixclone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflixclone
  template:
    metadata:
      labels:
        app: netflixclone
    spec:
      containers:
        - name: netflixclone
          image: ahmedmuraat/netflixclone:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: netflixclone-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: netflixclone
