apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-subscribe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-subscribe
  template:
    metadata:
      labels:
        app: db-subscribe
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: db-subscribe
          image: mcr.microsoft.com/mssql/server:2019-latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-secrets
                  key: mssql-sa-password-subscribe
            - name: MSSQL_PID
              value: developer
          volumeMounts:
            - name: subscribe-database-volume
              mountPath: /var/opt/mssql
      volumes:
        - name: subscribe-database-volume
          persistentVolumeClaim:
            claimName: subscribe-mssql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: db-subscribe
spec:
  selector:
    app: db-subscribe
  ports:
    - protocol: TCP
      port: 1435
      targetPort: 1433
