apiVersion: v1
kind: Service
metadata:
  name: locust-master
  namespace: default
spec:
  selector:
    app: locust
    role: master
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      name: web
    - protocol: TCP
      port: 5557
      targetPort: 5557
      name: master
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-master
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locust
      role: master
  template:
    metadata:
      labels:
        app: locust
        role: master
    spec:
      containers:
        - name: locust-master
          image: locustio/locust
          args: ["-f", "/mnt/locust/locustfile.py", "--master"]
          ports:
            - containerPort: 8089
            - containerPort: 5557
          volumeMounts:
            - name: locustfile
              mountPath: /mnt/locust
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: locustfile
          configMap:
            name: locustfile-configmap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
  namespace: default
spec:
  replicas: 3  # Adjusted replicas for 500 users
  selector:
    matchLabels:
      app: locust
      role: worker
  template:
    metadata:
      labels:
        app: locust
        role: worker
    spec:
      containers:
        - name: locust-worker
          image: locustio/locust
          args: ["-f", "/mnt/locust/locustfile.py", "--worker", "--master-host=locust-master"]
          volumeMounts:
            - name: locustfile
              mountPath: /mnt/locust
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: locustfile
          configMap:
            name: locustfile-configmap
