apiVersion: v1
kind: Secret
metadata:
  name: mssql-secrets
type: Opaque
data:
  mssql-sa-password: QUhtZWQxMjMh  # Base64 encoded "Ahmed123!"
  mssql-sa-password-userinfo: U2plZW1hYTEyIQ==  # Base64 encoded "Sjeemaa12!"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
type: Opaque
data:
  rabbitmq-default-user: dXNlcg==  # Base64 encoded "user"
  rabbitmq-default-pass: cGFzc3dvcmQ=  # Base64 encoded "password"