name: .NET Microservices CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ApiGateWay, Login, Subscription, Userdata]
    steps:
      - uses: actions/checkout@v3
        name: Check out the repo

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.project }}
          file: ./${{ matrix.project }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.project }}:latest

      - name: Build and push
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ matrix.project }}:latest -f ./${{ matrix.project }}/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ matrix.project }}:latest
