name: .NET Microservices CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [ApiGateWay, Login, Userdata, Subscription]
    steps:
      - uses: actions/checkout@v3
        name: Check out the repo

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install dependencies
        run: dotnet restore ./${{ matrix.project }}/${{ matrix.project }}.csproj

      - name: Build
        run: dotnet build --no-restore -c Release ./${{ matrix.project }}/${{ matrix.project }}.csproj

      - name: Test (optional)
        run: dotnet test --no-build -c Release ./${{ matrix.project }}/${{ matrix.project }}.csproj
        continue-on-error: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Lowercase project name for Docker tag
        id: lowercase
        run: echo "::set-output name=project::$(echo ${{ matrix.project }} | tr '[:upper:]' '[:lower:]')"

      - name: Build and Push Docker image
        run: |
          # Use the output from the 'lowercase' step
          LOWERCASE_PROJECT_NAME="${{ steps.lowercase.outputs.project }}"
          
          # Build the Docker image
          docker build -t ${{ secrets.DOCKER_USERNAME }}/$LOWERCASE_PROJECT_NAME:latest -f ./${{ matrix.project }}/Dockerfile ./${{ matrix.project }}
          
          # Push the Docker image to Docker Hub
          docker push ${{ secrets.DOCKER_USERNAME }}/$LOWERCASE_PROJECT_NAME:latest
